name: pet
description: com.my.app.pet

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^0.3.1
  dio: ^2.0.18
  json_annotation: ^2.0.0
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.2
  rxdart: ^0.20.0
  scoped_model: ^1.0.1
  flutter_swiper: ^1.1.6
  cached_network_image: ^0.7.0
  flutter_spinkit: ^3.1.0
  flutter_staggered_grid_view: ^0.2.7
  flutter_inappbrowser: 1.2.1
  flutter_cache_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/p1.png
    - assets/icons/p2.png
    - assets/icons/p3.png
    - assets/icons/p4.png
    - assets/icons/p5.png
    - assets/icons/p6.png
    - assets/icons/p7.png
    - assets/icons/p8.png
    - assets/icons/identification.png